### ISSUE TITLE
When subscribe to pza, add publish attributes (enable, voltage, current ...) for fakebpc

### ISSUE THREAD

**Issue by Darcraytore1** [Panduza/panduza-rust-platform#23]

**Comment by XdoctorwhoZ** [comment]
The attributes are probably not published as retained... I will check

**Comment by XdoctorwhoZ** [comment]
Ok, it seems, it is already good we need to check togehter

**Comment by XdoctorwhoZ** [comment]
@Darcraytore1 you can test again and tell me if the issue still remains

**Comment by Darcraytore1** [comment]
Yep now it's working properly 👍
