### ISSUE TITLE
Put platform name choose by the user in panduza local broker discovery answer

### ISSUE THREAD

**Issue by Darcraytore1** [Panduza/panduza-rust-platform#44]
@XdoctorwhoZ  Currenlty "panduza_platform" is always returned like name of the platform in the answer payload of the panduza local broker discovery function. So we need to put the actual platform name choosen by the user but this name must go on to be filled in the tree.json by the user ?

**Comment by XdoctorwhoZ** [comment]
change this 
```
let mut buf = [0; 1024];
let json_reply_bytes = "{\"name\": \"panduza_platform\",\"version\": 1.0}".as_bytes();
```
