### ISSUE TITLE
Linux failed to created connection.json if didn't exist and crash platform

### ISSUE THREAD

**Issue by Darcraytore1** [Panduza/panduza-rust-platform#46]
-1-[F] # Device factory initialization
-1-[F] List of producers:
-1-[F]   - korad.ka3005
-1-[F]   - new hunter
-1-[F]   - panduza.server
-1-[F]   - panduza.voxpower_inhibiter
-1-[F]   - panduza.fake_power_supply
-1-[P] Platform Version ...
-3-[P] Booting...
-3-WARN: Unsupported system bu try with unix path anyway !
\===========================================================
!
!
!
-3-WARN: Unsupported system bu try with unix path anyway !
No configuration file found ! (/etc/panduza/connection.json)
Do you want to create one with default settings ? [N/y]
y
-3-WARN: Unsupported system bu try with unix path anyway !
Failed to create default connection info: Permission denied (os error 13)
thread 'tokio-runtime-worker' panicked at src/platform/services/boot/connection_info_loading_process/mod.rs:60:14:
Failed to create default connection info: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
-1-ERROR: Join failed: task 3 panicked

**Comment by XdoctorwhoZ** [comment]
True, in Linux the required directory is /etc and you don't have the rights to write on it by default unless you are admin.

We have to think how to solve this

I can also see: **-3-WARN: Unsupported system bu try with unix path anyway !**

This is wierd, I will append some extra log in the function to test why linux is reported as "unsupported"
